sudo: false

notfications:
  email:
    on_success: never
    on_failure: never

language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install flake8

before_script:
  - flake8 .

script:
  - python -m unittest discover
